### PR TITLE
Add pre-commit workflow

### PR DESCRIPTION
**Pull request by inknos**

### CODE REVIEW

**Comment by inknos** [comment]
@jwhonce would you like to take a look at this?

cc: @lsm5 as it introduces some cirrus, make and automation changes

**Comment by lsm5** [comment]
@inknos not opposed to cirrus, but just wondering if we can do without cirrus? Can we achieve the same via TMT by any chance?

**Comment by lsm5** [comment]
> @inknos not opposed to cirrus, but just wondering if we can do without cirrus? Can we achieve the same via TMT by any chance?

I'm cool with dropping cirrus in a followup PR.

**Comment by jwhonce** [comment]
@inknos Please update https://github.com/containers/podman-py/blob/main/CONTRIBUTING.md to reflect the change of tools. Otherwise, looks good.

**Pull request merged**
