### PR TITLE
backports for v4.0.0

### PR DESCRIPTION
**Pull request by cdoern**
add support in 4.0 for healthcheck on failure actions

Signed-off-by: Charlie Doern <cdoern@redhat.com>

### CODE REVIEW

**Comment by cdoern** [comment]
@rhatdan @TomSweeneyRedHat PTAL, I think I did this right :)

**Comment by cdoern** [comment]
@jwhonce for this to work would we not need to backport these changes to 4.0 podman as well so that the json is valid? or am I missing something else as to why gating tests are failing

**Comment by TomSweeneyRedHat** [comment]
I was suspecting this would go against the v4.0.0 branch from upstream?  I'm not seeing a v4.0.0-rhel branch (at least at this moment).  @jwhonce PTAL

**Comment by TomSweeneyRedHat** [comment]
Code changes LGTM though, once the gating is figured out.  That might be related to the branch.

**Comment by cdoern** [comment]
> I was suspecting this would go against the v4.0.0 branch from upstream? I'm not seeing a v4.0.0-rhel branch (at least at this moment). @jwhonce PTAL

I am seeing a v4.2 branch and a v4.0.0-rhel branch (which I created)

**Comment by TomSweeneyRedHat** [comment]
This is where I was expecting to see the 4.2.0-release:  https://github.com/containers/podman-py/releases.  I'm only seeing the v4.2.0, v4.0.0, and a variety of v3.* branches there.  

I'm showing my Git release ignorance here, perhaps the v4.2.0-release branch will be created (or more likely you'll need to create it) after this merges.

**Comment by cdoern** [comment]
@TomSweeneyRedHat the tests look good locally

**Comment by TomSweeneyRedHat** [comment]
@cdoern, excellent, thanks for the update.  Are you preparing the v4.0.0-rhel branch and a new release for Jindrich?  Or do we have another delivery mechanism for him for tomorrow?

**Pull request merged**
