### PR TITLE
Cirrus: Modernize VM-based testing setup

### PR DESCRIPTION
**Pull request by cevich**

### CODE REVIEW

**Comment by cevich** [comment]
@jwhonce PTAL.

**Comment by cevich** [comment]
@jwhonce PTAL.  I updated VM images w/ necessary packages and tests are green.  I would suggest removing or de-coupling the environment setup (in the Makefile) [since it's negatively impacting runtime performance[*]](https://cirrus-ci.com/task/6147066582794240?command=main#L13).  It's probably fine to simply document the package requirements, as we do with podman.  Lastly, I left open the possibility of running the tests in a matrix on multiple platforms and versions.  Just let me know if/when you're ready for that, and I'll help make it happen. The automation/image changes required, are pretty minimal, getting the tests to pass everywhere is often the "hard part" :grin:

[*] The time consuming part is the repository-cache update (not the package install).  This can take multiple minutes, and the Fedora repository mirrors aren't always reliable - introducing an opportunity for automation-flakes.

**Comment by cevich** [comment]
@jwhonce PTAL - note: I stripped out the 'make env' to speed up and improve CI reliability.  Whole thing runs in about 3-minutes, of which 1-minute is waiting for the VM to start :grinning:

**Comment by cevich** [comment]
Update: Added documentation for package requirements

**Review by jwhonce — APPROVED** [review]
bors r+

**Comment by cevich** [comment]
bors retry

**Pull request merged**
