### PR TITLE
Update Makefile target to emulate readthedocs automation

### PR DESCRIPTION
**Pull request by jwhonce**
Major issue is readthedocs has fixed paths

Signed-off-by: Jhon Honce <jhonce@redhat.com>

### CODE REVIEW

**Comment by jwhonce** [comment]
@lsm5 Does any of the packaging tools use the Makefile docs target?

**Comment by lsm5** [comment]
so far, only the LICENSE and README.md files are installed by the fedora package as well as the podman-next copr package. So, nothing uses the Makefile docs target yet.

**Comment by lsm5** [comment]
Should the package be building and installing the docs too? I can set that up once this is merged.

**Comment by umohnani8** [comment]
@jwhonce are you still working on this?

**Comment by rhatdan** [comment]
@umohnani8 I think you can safely take it from him.

**Comment by jwhonce** [comment]
@umohnani8 I thought @baude had taken this over. Sorry if I dropped the ball here.

**Comment by umohnani8** [comment]
I can take this over and get it done. @jwhonce can you just tell me what exactly we are trying to do here? Is this PR good as is or are some additional changes needed?

**Comment by jwhonce** [comment]
@umohnani8 The goal was to have the Makefile target `docs` behaviour be the same as the readthedocs automation concerning where the formatted html landed etc. If my memory is correct it wasn't merged for fear of breaking packaging. Reading @lsm5 's comment it would appear to be safe to merge.

**Comment by umohnani8** [comment]
@lsm5 is this safe to merge now? Could we break packaging with this change?

**Comment by umohnani8** [comment]
Closing this in favor of https://github.com/containers/podman-py/pull/282 so we can run tests on latest ci.

**Pull request closed without merging**
