### PR TITLE
Remove duplicate base_url set from args

### LINKED ISSUE #88: PodmanClient fails with base_url defined: got multiple values for argument 'base_url'
By running the simple example it fails (installed from git master):

```python
>>> from podman import PodmanClient
>>> uri1 = "unix:///run/user/1000/podman/podman.sock"
>>> with PodmanClient(uri1) as client:
...     version = client.version()
```

```python
16:19:16.85 >>> Call to PodmanClient.__init__ in File "/home/sshnaidm/sources/podman-py/podman/client.py", line 38
16:19:16.85 .......... self = <podman.client.PodmanClient object at 0x7fb1bc99dca0>
16:19:16.85 .......... args = ('unix:///run/user/1000/podman/podman.sock',)
16:19:16.85 .......... len(args) = 1
16:19:16.85 .......... kwargs = {}
16:19:16.85 .......... __class__ = <class 'podman.client.PodmanClient'>
16:19:16.85   38 |     def __init__(self, *args, **kwargs) -> None:
16:19:16.85   63 |         super().__init__()
16:19:16.85   64 |         config = PodmanConfig()
16:19:16.85 .............. config = <podman.domain.config.PodmanConfig object at 0x7fb1bc99dc10>
16:19:16.85   66 |         api_kwargs = kwargs.copy()
16:19:16.85 .............. api_kwargs = {}
16:19:16.85   68 |         if "connection" in api_kwargs:
16:19:16.85   74 |         elif "base_url" not in api_kwargs:
16:19:16.86   75 |             path = str(
16:19:16.86   76 |                 Path(xdg.BaseDirectory.get_runtime_dir(strict=False)) / "podman" / "podman.sock"
16:19:16.86   75 |             path = str(
16:19:16.86 .................. path = '/run/user/1000/podman/podman.sock'
16:19:16.86   78 |             api_kwargs["base_url"] = "http+unix://" + path
16:19:16.86 .................. api_kwargs = {'base_url': 'http+unix:///run/user/1000/podman/podman.sock'}
16:19:16.86 .................. len(api_kwargs) = 1
16:19:16.86   79 |         self.api = APIClient(*args, **api_kwargs)
16:19:16.86 !!! TypeError: __init__() got multiple values for argument 'base_url'
16:19:16.86 !!! When calling: APIClient(*args, **api_kwargs)
16:19:16.86 !!! Call ended by exception
2021-05-10 16:19:16.862 | ERROR    | __main__:<module>:1 - An error has been caught in function '<module>', process 'MainProcess' (281384), thread 'MainThread' (140403397965632):
Traceback (most recent call last):

  File "/home/sshnaidm/venvs/py2/lib/python2.7/site-packages/dreampielib/data/subp_main.py", line 44, in <module>
    main()
    └ <function main at 0x7fb2292f4670>

  Fi
Traceback (most recent call last):
  File "<pyshell#5>", line 2, in <module>
    version = client.version()
  File "/home/sshnaidm/sources/podman-py/podman/client.py", line 203, in version
    def version(self, *args, **kwargs):  # pylint: disable=missing-function-docstring
  File "/usr/lib64/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/home/sshnaidm/sources/podman-py/podman/client.py", line 174, in system
    @cached_property
AttributeError: 'PodmanClient' object has no attribute 'api'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#5>", line 2, in <module>
    version = client.version()
  File "/home/sshnaidm/sources/podman-py/podman/client.py", line 85, in __exit__
  File "/home/sshnaidm/sources/podman-py/podman/client.py", line 209, in close
    def close(self):
AttributeError: 'PodmanClient' object has no attribute 'api'
le "/home/sshnaidm/venvs/py2/lib/python2.7/site-packages/dreampielib/data/subp_main.py", line 41, in main
    subprocess_main(port)
    │               └ 10020
    └ <function main at 0x7fb22901d790>

  File "/home/sshnaidm/venvs/py2/lib/python2.7/site-packages/dreampielib/data/subp-py3/dreampielib/subprocess/__init__.py", line 1060, in main
    _subp = Subprocess(port)
            │          └ 10020
            └ <class 'dreampielib.subprocess.Subprocess'>

  File "/home/sshnaidm/venvs/py2/lib/python2.7/site-packages/dreampielib/data/subp-py3/dreampielib/subprocess/__init__.py", line 233, in __init__
    self.loop()
    │    └ <function Subprocess.loop at 0x7fb2290184c0>
    └ <dreampielib.subprocess.Subprocess object at 0x7fb229304460>

  File "/home/sshnaidm/venvs/py2/lib/python2.7/site-packages/dreampielib/data/subp-py3/dreampielib/subprocess/__init__.py", line 245, in loop
    for obj in r:
        │      └ <generator object Subprocess.execute at 0x7fb1bc994cf0>
        └ (True, None)

  File "/home/sshnaidm/venvs/py2/lib/python2.7/site-packages/dreampielib/data/subp-py3/dreampielib/subprocess/__init__.py", line 433, in execute
    exec(codeob, self.locs)
         │       │    └ {'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': None, '__spec__': None, '__builtins__': {'__name...
         │       └ <dreampielib.subprocess.Subprocess object at 0x7fb229304460>
         └ <code object <module> at 0x7fb2284ad030, file "<pyshell#5>", line 1>

> File "<pyshell#5>", line 1, in <module>
    with PodmanClient(uri1) as client:
         │            │        └ <podman.client.PodmanClient object at 0x7fb229088c70>
         │            └ 'unix:///run/user/1000/podman/podman.sock'
         └ <class 'podman.client.PodmanClient'>
  File "/home/sshnaidm/.local/lib/python3.9/site-packages/snoop/tracer.py", line 170, in simple_wrapper
    return function(*args, **kwargs)
           │         │       └ {}
           │         └ (<podman.client.PodmanClient object at 0x7fb1bc99dca0>, 'unix:///run/user/1000/podman/podman.sock')
           └ <function PodmanClient.__init__ at 0x7fb1bc984040>

  File "/home/sshnaidm/sources/podman-py/podman/client.py", line 79, in __init__
    self.api = APIClient(*args, **api_kwargs)
    │          │          │       └ {'base_url': 'http+unix:///run/user/1000/podman/podman.sock'}
    │          │          └ ('unix:///run/user/1000/podman/podman.sock',)
    │          └ <class 'podman.api.client.APIClient'>
    └ <podman.client.PodmanClient object at 0x7fb1bc99dca0>

TypeError: __init__() got multiple values for argument 'base_url'
```

### PR DESCRIPTION
**Pull request by sshnaidm**
Fix #88

### CODE REVIEW

**Comment by jwhonce** [comment]
@cevich PTAL

**Comment by sshnaidm** [comment]
probably need to fix also readme?

**Comment by jwhonce** [comment]
@sshnaidm Good catch. Thank you for your PR. There are a number of places I gave examples and didn't include the keyword `base_url` if you could search and fix them all that would be great!

**Comment by jwhonce** [comment]
@sshnaidm I missed that you had not signed this PR. Please do, see below if you do not know how.

```
git commit -a --amend -s
git push --force
```

**Pull request merged**
