### PR TITLE
Fix assertation error in manifest.py

### PR DESCRIPTION
**Pull request by umohnani8**

### CODE REVIEW

**Comment by jwhonce** [comment]
LGTM, did api change?

**Comment by umohnani8** [comment]
@jwhonce I don't think so, I don't see any changes to manifest remove digest in the recent podman history. I wonder if the functionality of `assertIsNone` changed? Any idea where I can confirm that?

**Comment by umohnani8** [comment]
Hmm, nvm `assertIsNone` is a part of unittest, so don't think that changed. I am not sure where the api might have possibly changed to have `manifests` be an empty list instead of `None`

**Comment by andryyy** [comment]
Strange.

I just tried Podman 4.3.something on Debian 12 and testing with podman-py's current stable as well as the code from the main branch. It always returned None. Same when I upgraded Podman to 4.5.1 from the Kubic repository.

I compiled Podman 4.7.0-dev on the same system and just then it returned an empty list.

Didn't try 4.6 though.

I mirrored the socket with socat and compared the request and response:

```
# socat -t100 -x -v UNIX-LISTEN:/home/user/podman-mirror.sock,mode=777,reuseaddr,fork UNIX-CONNECT:/run/user/1000/podman/podman.sock

# Result dev:

GET /v4.7.0/libpod/manifests/localhost%2Funittest%2Falpine/json HTTP/1.1\r
Host: %2fhome%2fuser%2fpodman-mirror.sock\r
User-Agent: PodmanPy/4.7.0-dev (API v4.7.0; Compatible v1.40)\r
Accept-Encoding: gzip, deflate\r
Accept: */*\r
Connection: keep-alive\r
\r
< 2023/09/01 08:51:33.000905957  length=330 from=1781 to=2110
HTTP/1.1 200 OK\r
Api-Version: 1.41\r
Content-Type: application/json\r
Libpod-Api-Version: 4.7.0-dev\r
Server: Libpod/4.7.0-dev (linux)\r
X-Reference-Id: 0xc000123888\r
Date: Fri, 01 Sep 2023 06:51:33 GMT\r
Content-Length: 107\r
\r
{"schemaVersion":2,"mediaType":"application/vnd.docker.distribution.manifest.list.v2+json","manifests":[]}

# Result v4.5.1:

GET /v4.7.0/libpod/manifests/localhost%2Funittest%2Falpine/json HTTP/1.1\r
Host: %2fhome%2fuser%2fpodman-mirror.sock\r
User-Agent: PodmanPy/4.7.0-dev (API v4.7.0; Compatible v1.40)\r
Accept-Encoding: gzip, deflate, zstd\r
Accept: */*\r
Connection: keep-alive\r
\r
< 2023/09/01 08:56:39.000681039  length=324 from=374 to=697
HTTP/1.1 200 OK\r
Api-Version: 1.41\r
Content-Type: application/json\r
Libpod-Api-Version: 4.5.1\r
Server: Libpod/4.5.1 (linux)\r
X-Reference-Id: 0xc000030710\r
Date: Fri, 01 Sep 2023 06:56:39 GMT\r
Content-Length: 109\r
\r
{"schemaVersion":2,"mediaType":"application/vnd.docker.distribution.manifest.list.v2+json","manifests":null}
```

I think this happened somewhere in [this commit](https://github.com/containers/podman/commit/f33b01b7312f86cb4b2d0428e10e4b9318193c4d) by changing the decoder in https://github.com/containers/podman/blame/main/pkg/api/handlers/decoder.go

**Pull request merged**
