### PR TITLE
Add additional image calls

### PR DESCRIPTION
**Pull request by mwhahaha**
Add a call to allow for image tagging and an example of what is expected for POST data.

### CODE REVIEW

**Comment by rhatdan** [comment]
@mwhahaha Thanks, but you have to sign your commits.

git commit -a --amend -s
git push --force

@jwhonce PTAL

**Comment by mwhahaha** [comment]
Done i need to get used to the -s thing

**Comment by rhatdan** [comment]
@mwhahaha You are failing the linting tests.

**Comment by mwhahaha** [comment]
yea i'm going to take over #27 and then clean this one up. There's some various linting issues in tree as is so i'll clean them up with a different PR and come back to this

**Comment by jwhonce** [comment]
@mwhahaha Please rebase

**Comment by rhatdan** [comment]
LGTM

**Comment by jwhonce** [comment]
bor r+

**Pull request merged**
