### PR TITLE
Fixup lint items

### PR DESCRIPTION
**Pull request by mwhahaha**
This change switches to using fstrings for url paths and addresses
additional new linting rules.

Newer pylint versions have some new rules which we're triggering

* inconsistent-return-statements (2.7)
* arguments-renamed (2.9)
* unspecified-encoding (2.10)
* use-list-literal (2.10)
* use-dict-literal (2.10)
* consider-using-f-string (2.11)

Disabled few options until the CI version is upgraded past 2.9

* duplicate-code
* bad-option-value

### CODE REVIEW

**Comment by mwhahaha** [comment]
@jwhonce fyi this has the various things. If you use the packaged pylint it's older and missing things. If you run tox, you get the latest

**Comment by jwhonce** [comment]
@mwhahaha Work looks good. Happy to merge once tests go green

Additionally,  I am thinking it is time to remove the old code/API and just support the compatible API. 

In my IDE, I am using the following options for pylint(2.9.6) "--msg-template='{abspath}:{line},{column}: {msg} ({symbol})'" --output-format=colorized --max-line-length=100 --disable=fixme --ignore tests podman

**Comment by rhatdan** [comment]
@cevich I think we should update the images that these tests are based on to F35

**Comment by cevich** [comment]
> I think we should update the images that these tests are based on to F35

Oh, woops, I missed this repo...

**Comment by cevich** [comment]
...https://github.com/containers/podman-py/pull/158

**Pull request merged**
