### PR TITLE
Add read_write_tmpfs

### PR DESCRIPTION
**Pull request by msisj**
Added possibility to alter `read_write_tmpfs` option

### CODE REVIEW

**Comment by umohnani8** [comment]
/approve
LGTM
@rhatdan @lsm5 @jwhonce PTAL

**Review by lsm5 — APPROVED** [review]
LGTM.

@cevich can I get your eyes on this please?

**Review by cevich — APPROVED** [review]
LGTM w/ caveat: I don't know this API or Code.  Otherwise, I have a basic understanding of what this does and tests.  The test is really well written and very clear/concise.  Nice job!

**Pull request merged**
