### PR TITLE
Streaming support for PodsManager.stats API

### PR DESCRIPTION
**Pull request by RazCrimson**
Podman API supports streaming Pod stats, but podman-py does not support that as of now.

This PR aims to add support for that.

### CODE REVIEW

**Comment by umohnani8** [comment]
@RazCrimson I believe tests should pass now once you rebase

**Comment by RazCrimson** [comment]
@umohnani8 
Thanks for the reminder. PTAL.

**Comment by umohnani8** [comment]
LGTM
@rhatdan @lsm5 PTAL

**Review by lsm5 — APPROVED** [review]
LGTM in my limited capacity, I'll defer to @umohnani8 and @rhatdan

**Pull request merged**
