### PR TITLE
Add progress_bar option to image pull

### PR DESCRIPTION
**Pull request by umohnani8**
Add a new arg option called progress_bar that when set to true will display a progress bar with the image pull progress. This uses the compat endpoint as that is the data we are able to parse to displat the progress bar.

### CODE REVIEW

**Comment by umohnani8** [comment]
This is what the progress bar looks like - it is basically a bar for each layer being pulled and switches from Download to Download complete when done.

Screenshot from 2023-11-09 11-09-56

**Comment by umohnani8** [comment]
Gating will fail till https://github.com/containers/podman-py/pull/339 is merged.

I also don't see a way of adding tests for this.

@jwhonce @baude @rhatdan @lsm5 PTAL

**Comment by rhatdan** [comment]
Nice work

LGTM

**Comment by umohnani8** [comment]
@jwhonce @baude @cevich @lsm5 tests are green! PTAL

**Review by lsm5 — APPROVED** [review]
/lgtm
/hold

**Pull request merged**
