### PR TITLE
update urllib to 1.26.5 for a CVE found in previous versions

### PR DESCRIPTION
**Pull request by cdoern**
resolves https://github.com/advisories/GHSA-wqvq-5m8c-6g24
https://issues.redhat.com/browse/OCPBUGS-1926

Signed-off-by: Charlie Doern <cdoern@redhat.com>

### CODE REVIEW

**Comment by cdoern** [comment]
@TomSweeneyRedHat PTAL I think this is what is needed

**Comment by jwhonce** [comment]
@cdoern Have you verified that version of the urllib3 library is available on RHEL and the other supported OSes?  That has been an issue in the past. Otherwise,  you lucked out that the version bump didn't break requests library. That has been an issue in the past.

/cc @lsm5 @jnovy

**Comment by TomSweeneyRedHat** [comment]
Yes, please include the full CVE in the commit message.  Also, in the description or a comment, please include a link to the BZ that this is fixing.  As far as the versions go, Jindrich is the man to check with.

**Comment by rhatdan** [comment]
@cdoern Please update so we can merge.

**Comment by cdoern** [comment]
sorry for the delay, I think this is set.

**Pull request merged**
