### PR TITLE
Add python 3.12 support and remove python xdg

### PR DESCRIPTION
**Pull request by inknos**
related to https://github.com/containers/podman-py/issues/397

### CODE REVIEW

**Comment by lsm5** [comment]
packit builds are happy, that's good. 

@inknos i think it would be nice to get this in before we cut 5.1 release. wdyt? cc @jwhonce

**Comment by rhatdan** [comment]
LGTM although linter is not happy.

**Comment by inknos** [comment]
sorry for the noise. my local env is faulty and does not have the same results that github for black and pylint. I fixed the linter now

**Review by lsm5 — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
