### PR TITLE
Correctly add secrets to container on creation

### PR DESCRIPTION
**Pull request by timc**
Signed-off-by: Tim Carpenter <timc@users.noreply.github.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@jwhonce @cdoern @mwhahaha @umohnani8 PTAL

**Comment by umohnani8** [comment]
changes LGTM
tests should pass after https://github.com/containers/podman-py/pull/236 is merged

**Comment by umohnani8** [comment]
@timc please rebase to pick up test fixes

**Comment by umohnani8** [comment]
@timc looks like lint is unhappy about a line in your code, can you please fix that and repush https://github.com/containers/podman-py/pull/234/checks?check_run_id=11211238911

**Comment by timc** [comment]
@umohnani8 sorry about that, looks like everything passes now.

**Pull request merged**
