### PR TITLE
Correct "ports" keyword for container create

### PR DESCRIPTION
**Pull request by jwhonce**
* Corrected for field
* Added tests to ensure field is used correctly

Signed-off-by: Jhon Honce <jhonce@redhat.com>

### CODE REVIEW

**Comment by jwhonce** [comment]
@containers/podman-maintainers @mwhahaha PTAL

**Comment by JacobCallahan** [comment]
When testing locally, the result looks great!
```python
cont = pman.containers.create("postgres", ports={"22":1337, "23":1445})
cont.ports == {
   '22/tcp': [{'HostIp': '', 'HostPort': '1337'}],
   '23/tcp': [{'HostIp': '', 'HostPort': '1445'}]
}
```

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
