### PR TITLE
Fix portmapping in container creation

### PR DESCRIPTION
**Pull request by sshnaidm**
Fix typos for 'portmapping', align types with documentation,
change way it's parsed.

### CODE REVIEW

**Comment by mwhahaha** [comment]
failure looks unrelated, will need to investigate that

**Comment by mwhahaha** [comment]
I think https://github.com/containers/podman/commit/a9cb824981 broke the image test because it uses ".containerfile.<numbers>" for the 'dockerfile' parameter which wouldn't be valid json (if i'm reading the patch correctly).

@rhatdan would you be able to confirm my theory related to tthe current test failure being reported

```
======================================================================
ERROR: test_build (integration.test_images.ImagesIntegrationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/go/src/github.com/containers/podman-py/podman/tests/integration/test_images.py", line 124, in test_build
    image, stream = self.client.images.build(fileobj=buffer)
  File "/var/tmp/go/src/github.com/containers/podman-py/podman/domain/images_build.py", line 117, in build
    response.raise_for_status(not_found=ImageNotFound)
  File "/var/tmp/go/src/github.com/containers/podman-py/podman/api/client.py", line 65, in raise_for_status
    raise APIError(cause, response=self._response, explanation=message)
podman.errors.exceptions.APIError: 400 Client Error: Bad Request (failed to parse query parameter 'dockerfile': ".containerfile.7b009fd145dab2008d411bd3f4f3ef34cdd67b42": invalid character '.' looking for beginning of value)
```

**Comment by sshnaidm** [comment]
> @mwhahaha: No presubmit jobs available for containers/podman-py@main

Probably need to redefine them from "master" to "main", @jwhonce ?

**Review by mwhahaha — APPROVED** [review]

**Pull request merged**
