### PR TITLE
Include py.typed marker file.

### PR DESCRIPTION
**Pull request by jonded94**
I'm using this package in codebases checked with common static type checking tools, such as `mypy`. Unfortunately, it will error:
```
error: Skipping analyzing "podman": module is installed, but missing library stubs or py.typed marker  [import]
```

This was already apparent in https://github.com/containers/podman-py/issues/293. Including this file would at least enable checking against the many type hints that are already a part of this library and would help massively.

### CODE REVIEW

**Comment by jwhonce** [comment]
@jnsnow PTAL, TIA

**Comment by umohnani8** [comment]
Thank you @jonded94! Can you please rebase with upstream and sign your commit and repush, I think that should help fix the DCO and gating failure.

Changes LGTM

**Comment by jonded94** [comment]
Did a rebase and a force repush, with a signed commit (which also shows to be verified in Github), but unfortunately that DCO job still fails?

**Comment by umohnani8** [comment]
I believe DCO is failing because your commit doesn't have the `Signed off by...` line it. Can you please ensure `git commit -s --amend` adds that for you and then repush.

**Comment by jonded94** [comment]
Tests seem to run through now, thanks for your help!

**Comment by rhatdan** [comment]
/approve
/lgtm
Thanks @jonded94

**Pull request merged**
