### PR TITLE
Bump version to 4.5.0

### PR DESCRIPTION
**Pull request by umohnani8**

### CODE REVIEW

**Comment by umohnani8** [comment]
@rhatdan @lsm5 PTAL

**Review by lsm5 — APPROVED** [review]
/lgtm

**Comment by jwhonce** [comment]
LGTM

**Comment by lsm5** [comment]
is mergebot supposed to work here, or just one of those slow days?

**Comment by lsm5** [comment]
> @lsm5 I think mergebot took a hike sometime in the fall. Do you want to hit the big green button?

ack, cause it seems to be working fine on the other repos. I'll hit merge. Thanks @jwhonce

**Comment by jwhonce** [comment]
@lsm5 maybe a configuration issue?

**Pull request merged**
