### PR TITLE
Bump version to 5.1.0

### PR DESCRIPTION
**Pull request by inknos**
cc: @jwhonce

### CODE REVIEW

**Comment by jwhonce** [comment]
@inknos you missed podman/tests/__init__.py . The API version is hard coded in the tests to ensure review of the API when changing the version number.

**Comment by inknos** [comment]
> you missed podman/tests/init.py . The API version is hard coded in the tests to ensure review of the API when changing the version number.

Thanks John I was actually counting on you because I didn't know what was the issue right away, and I started working on something else.

**Comment by jwhonce** [comment]
LGTM

**Comment by jwhonce** [comment]
PTAL @umohnani8

**Pull request merged**
