### PR TITLE
Accept integer ports in containers_create.create

### PR DESCRIPTION
**Pull request by krrhodes**
Currently in containers_create.create(), the ports dict parameter is described as
    
> The keys of the dictionary are the ports to bind inside the container, either as an integer or a string in the form port/protocol
    
however, if the dict passed as this parameter has an integer as a key, it will result in a TypeError from the code on L625 `if "/" in container`.
    
Fix this by casting any integer keys to be strings beforehand.

### CODE REVIEW

**Comment by inknos** [comment]
@krrhodes we fixed the testing issue. could you pull main and rebase your PR against it please?

**Comment by krrhodes** [comment]
@inknos Thanks! Done

**Review by inknos — CHANGES_REQUESTED** [review]
I'd like to see a test for this change. Something simple like this would probably work, what do you think? I am open to more ideas if you'd like to play around with the tests

```diff
diff --git a/podman/tests/integration/test_containers.py b/podman/tests/integration/test_containers.py
index 0fe0363..46bc53a 100644
--- a/podman/tests/integration/test_containers.py
+++ b/podman/tests/integration/test_containers.py
@@ -43,7 +43,7 @@ class ContainersIntegrationTest(base.IntegrationTest):

         with self.subTest("Create from Alpine Image"):
             container = self.client.containers.create(
-                self.alpine_image, command=["echo", random_string], ports={'2222/tcp': 3333}
+                self.alpine_image, command=["echo", random_string], ports={'2222/tcp': 3333, 2244: 3344}
             )
             self.assertIsInstance(container, Container)
             self.assertGreater(len(container.attrs), 0)
@@ -63,6 +63,9 @@ class ContainersIntegrationTest(base.IntegrationTest):
             self.assertEqual(
                 "3333", container.attrs["NetworkSettings"]["Ports"]["2222/tcp"][0]["HostPort"]
             )
+            self.assertEqual(
+                "3344", container.attrs["NetworkSettings"]["Ports"]["2244/tcp"][0]["HostPort"]
+            )

         file_contents = b"This is an integration test for archive."
         file_buffer = io.BytesIO(file_contents)
```

**Comment by inknos** [comment]
@krrhodes any update on this? :)

**Comment by krrhodes** [comment]
@inknos Hey! Busy week at work :), getting some tests set up now. It seems like it could make sense to include as part of both container create integration tests and containerManager unit tests, so I have included both, but if you think this is adding clutter/overdoing it, let me know and I can strip down

**Review by inknos — APPROVED** [review]

**Pull request merged**
