### PR TITLE
Support passing of interval and condition in podman wait calls

### PR DESCRIPTION
**Pull request by cdoern**
Signed-off-by: Charlie Doern <cdoern@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@mwhahaha @mheon @TomSweeneyRedHat @jwhonce @baude PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
Looks like I'll merge it the old-fashioned way.

**Pull request merged**
