### PR TITLE
[v4.4-rhel] Revert "Use modern tomllib/tomli modules for reading TOML files"

### PR DESCRIPTION
**Pull request by umohnani8**
This reverts commit c5a356fb4ea8a6fb66a6d20bdc2c9cffe615028b.

Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

### CODE REVIEW

**Comment by umohnani8** [comment]
@rhatdan @lsm5 PTAL
Will cut a v4.4.1 after this

**Comment by lsm5** [comment]
@umohnani8 do we need a -rhel branch given that we're reverting to toml on the main branch itself?

**Comment by lsm5** [comment]
> @umohnani8 do we need a -rhel branch given that we're reverting to toml on the main branch itself.

If the branch was created for other reasons, then don't mind me :D

**Comment by umohnani8** [comment]
The branch is created to track any backports that may need to go into 4.4 so we can cut new 4.4.x from there. So even though we are fixing this in main too, I would like to have a commit to the rhel-4.4 branch so we can cut a 4.4.1 from there instead of main to keep things aligned.

**Review by lsm5 — APPROVED** [review]
/lgtm

**Comment by lsm5** [comment]
for whatever reason, mergebot didn't merge even an hour after PR was good to go.

**Pull request merged**
