### PR TITLE
Fix readthedocs yaml

### PR DESCRIPTION
**Pull request by umohnani8**
Builds on readthedocs was failing due to a new requirement in the yaml. Fix that to get the builds working again.

### CODE REVIEW

**Comment by umohnani8** [comment]
@lsm5 @rhatdan @baude PTAL

**Comment by baude** [comment]
LGTM

**Comment by umohnani8** [comment]
@cevich @jwhonce can I get a lgtm here please

**Comment by TomSweeneyRedHat** [comment]
@GabiNecasova FYI

**Pull request merged**
