### PR TITLE
Cirrus: Make use of shared get_ci_vm container

### PR DESCRIPTION
**Pull request by cevich**
***WARNING***: DO NOT MERGE YET.  Core get_ci_vm container script not yet reviewed/finalized.

Depends on:
    https://github.com/containers/automation_images/pull/57
    https://github.com/containers/automation/pull/64
    https://github.com/containers/automation/pull/66
    https://github.com/containers/automation/pull/67
    https://github.com/containers/automation/pull/68

Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
Script updated to allow passing in `$DEBUG`

**Comment by cevich** [comment]
@jwhonce PTAL (and try it out, if you're able)

**Comment by rhatdan** [comment]
@cevich Needs a rebase.

**Comment by cevich** [comment]
oh woopsie...yep, okay fixed.

**Pull request merged**
