### PR TITLE
Support passing of interval and condition in podman wait calls

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@cdoern Could you take this one over.  Would like to get it in, but I have no time to work on it.

**Comment by cdoern** [comment]
> @cdoern Could you take this one over. Would like to get it in, but I have no time to work on it.

sure

**Comment by rhatdan** [comment]
That is fine with me.

**Comment by rhatdan** [comment]
@cdoern any progress.

**Comment by cdoern** [comment]
> @cdoern any progress.

This is on my docket for today, I think I'll be able to get it done relatively easily I started looking at it on Tuesday.

**Comment by cdoern** [comment]
@rhatdan do you want me to make a separate PR based off of your changes? I just rebased against your branch.

**Comment by rhatdan** [comment]
Yes you can just grab the work I have done and complete it.

**Pull request closed without merging**
