### PR TITLE
tox: test with python 3.11

### PR DESCRIPTION
**Pull request by lsm5**
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

@cdoern @jwhonce PTAL

### CODE REVIEW

**Review by cdoern — APPROVED** [review]
LGTM, any actual testing changes we need to make here?

**Comment by lsm5** [comment]
> LGTM, any actual testing changes we need to make here?

dunno, i'll defer to @jwhonce

**Comment by jwhonce** [comment]
/lgtm 

There are some warnings about deprecated code both are in other packages so looking good!

.tox/py311/lib/python3.11/site-packages/pkg_resources/_vendor/pyparsing.py:87
  /var/tmp/go/src/github.com/containers/podman-py/.tox/py311/lib/python3.11/site-packages/pkg_resources/_vendor/pyparsing.py:87: DeprecationWarning: module 'sre_constants' is deprecated
    import sre_constants

.tox/py311/lib/python3.11/site-packages/testtools/testresult/real.py:25
  /var/tmp/go/src/github.com/containers/podman-py/.tox/py311/lib/python3.11/site-packages/testtools/testresult/real.py:25: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
    import cgi

**Pull request merged**
