### PR TITLE
add support for healthcheck on failure actions for 4.2.0

### PR DESCRIPTION
**Pull request by cdoern**
Signed-off-by: Charlie Doern <cdoern@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Why was .cirrus.yml deleted?

**Comment by rhatdan** [comment]
Other changes LGTM

**Comment by cdoern** [comment]
> Why was .cirrus.yml deleted?

cirrus does not have the images for podman-py going back this far, @cevich and I are going to figure out a solution for future releases

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
I think you were doing a point release for Jindrich, if so, please create one in the morning.

**Comment by cevich** [comment]
> cirrus does not have the images for podman-py going back this far,

It's worse than that - we're not monitoring CI on any branch other than main for this repo.  That will eventually lead to images being pruned beyond 30-days of inactivity.  This stance can change for future release-branches if needed, but there's nothing I can do to recover CI VM images beyond 60-days of last CI activity.

**Pull request merged**
