### PR TITLE
Refactor network container options for podman 4.0

### PR DESCRIPTION
**Pull request by msisj**
Signed-off-by: Jankowiak Szymon-PRFJ46 <szymon.jankowiak@motorolasolutions.com>

As some networking options are no longer a thing, they were still in podman-py 4.0.
Definitely there are more of them but so far I've encountered these.
Those removed are in podman 3.4 but not in 4.0.
Option added is a new option in 4.0.
For reference please check : 
3.4 - https://docs.podman.io/en/latest/_static/api.html?version=v3.4#operation/ContainerCreateLibpod
latest - https://docs.podman.io/en/latest/_static/api.html#operation/ContainerCreateLibpod

After changes : 
```
>>> import podman
>>> client = podman.PodmanClient(base_url='unix:///run/podman/podman.sock')
>>> networks = {
...     "somenetwork": {
...          "aliases": ["test-alias"]
...     }
... }
>>> c1 = client.containers.create(name='test', image='test_image', command=['/bin/sleep', '12345'], networks=networks)
>>> print(c1.attrs["NetworkSettings"]["Networks"])
{'somenetwork': {'EndpointID': '', 'Gateway': '', 'IPAddress': '', 'IPPrefixLen': 0, 'IPv6Gateway': '', 'GlobalIPv6Address': '', 'GlobalIPv6PrefixLen': 0, 'MacAddress': '', 'NetworkID': 'somenetwork', 'DriverOpts': None, 'IPAMConfig': None, 'Links': None, 'Aliases': ['test-alias', 'd0239b151a21']}}
>>>
```

### CODE REVIEW

**Comment by msisj** [comment]
@jwhonce I'm wondering what I can do about failed validation. If I understand it correctly it has problem with my commit message being too long. But it was already pushed and I'm not sure whether I'm allowed to force push to change commit message? Should I ignore it or can I fix it somehow ?

**Comment by jwhonce** [comment]
@msisj If I understand correctly:

```sh
git commit --amend
```
Edit commit...
```sh
git push origin HEAD --force
```
`origin` above is my remote repository on github. Github will update the PR automatically.

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
