### PR TITLE
fix: name filter in images.list()

### PR DESCRIPTION
**Pull request by Mr-Sunglasses**
fix: #457

### CODE REVIEW

**Review by inknos — CHANGES_REQUESTED** [review]
hey @Mr-Sunglasses thanks for the PR. it looks good although there are a few things that the CI is complaining about, I can take a look into these as they seem unrelated.

The PR is good. Would you like to write some tests for filter?

You can take inspiration from these prs https://github.com/containers/podman-py/pull/462 https://github.com/containers/podman-py/pull/460 and if you have questions I can help you if you need

**Comment by Mr-Sunglasses** [comment]
> hey @Mr-Sunglasses thanks for the PR. it looks good although there are a few things that the CI is complaining about, I can take a look into these as they seem unrelated.
> 
> The PR is good. Would you like to write some tests for filter?
> 
> You can take inspiration from these prs #462 #460 and if you have questions I can help you if you need

Thanks a lot @inknos for the suggestions, I've added the tests for the filter and they are passing.

Also, I investigate on why the test's are failing, the reason seems for the test's failing, `The code is not compatible with Python 3.6` , I think we should drop the support of python 3.6 as I no longer support by Python Team IMO we should drop `3.6, 3.7, 3.8` ( Ref. [Python unsupported-versions](https://devguide.python.org/versions/#unsupported-versions) I'm looking forward to your views on this topic.

Thanks again, Looking forward to contribute more to the project!

**Comment by Mr-Sunglasses** [comment]
> > hey @Mr-Sunglasses thanks for the PR. it looks good although there are a few things that the CI is complaining about, I can take a look into these as they seem unrelated.
> > 
> > The PR is good. Would you like to write some tests for filter?
> > 
> > You can take inspiration from these prs #462 #460 and if you have questions I can help you if you need
> 
> Thanks a lot @inknos for the suggestions, I've added the tests for the filter and they are passing.
> 
> Also, I investigate on why the test's are failing, the reason seems for the test's failing, `The code is not compatible with Python 3.6` , I think we should drop the support of python 3.6 as I no longer support by Python Team IMO we should drop `3.6, 3.7, 3.8` ( Ref. [Python unsupported-versions](https://devguide.python.org/versions/#unsupported-versions) I'm looking forward to your views on this topic.
> 
> Thanks again, Looking forward to contribute more to the project!

cc. @rhatdan @inknos

**Comment by inknos** [comment]
whops, I missed your first update, sorry.

> Also, I investigate on why the test's are failing, the reason seems for the test's failing, The code is not compatible with Python 3.6 , I think we should drop the support of python 3.6 as I no longer support by Python Team IMO we should drop 3.6, 3.7, 3.8 ( Ref. [Python unsupported-versions](https://devguide.python.org/versions/#unsupported-versions) I'm looking forward to your views on this topic.

Agree. it's been a topic for a while, but I think the times are mature now and we can drop these versions from upstream

Let's proceed this way: I will make a pr to drop python and fix the tests, then we can merge this and also I'll bundle your changes in 5.3.0

**Comment by inknos** [comment]
@jwhonce this PR has test issues that are unrelated to the code. [This PR](https://github.com/containers/podman-py/pull/469) is dropping py<3.8 and bumping the release to 5.3.0, and it's a fix. 

However, I'd like to see this merged first to include it in the release. Are you ok with me merging, bypassing protections?

**Review by inknos — APPROVED** [review]

**Pull request merged**
