### PR TITLE
[CI:DOCS] Fix docs links due to branch rename

### PR DESCRIPTION
**Pull request by cevich**
Ref: https://github.com/containers/common/issues/549

Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
I'm guessing test failure is addressed by https://github.com/containers/podman-py/pull/110

This PR is also likely completely safe to force-merge.

**Comment by mwhahaha** [comment]
no we don't currently have a fix for CI. i'm trying to take a look at it today but i think the fix is on the podman side not the podman-py side

**Comment by cevich** [comment]
> no we don't currently have a fix for CI

Oh okay, thanks for the correction and update.

**Comment by mwhahaha** [comment]
This needs a rebase to pass CI. CI should be good.

**Review by mwhahaha — APPROVED** [review]
/lgtm

**Pull request merged**
