### PR TITLE
[release-4.6] Fix dns_option typo and add test of container create with DNS option

### PR DESCRIPTION
**Pull request by Honny1**
This PR backports fixes a typo in dns_option and adds a DNS option container creation test to version 4.6.

Fixes: https://issues.redhat.com/browse/RHEL-31069

### CODE REVIEW

**Comment by Honny1** [comment]
@inknos Unfortunately this didn't help probably will have to backport the other commits. What commits should I backport next?

**Comment by TomSweeneyRedHat** [comment]
@jwhonce any thoughts on the errors in this PR?

**Comment by inknos** [comment]
There is a chain of fixes [here](https://github.com/containers/podman-py/pull/450) then [here](https://github.com/containers/podman-py/pull/430)

**Comment by inknos** [comment]
since https://github.com/containers/podman-py/pull/449 jobs passed I want to give one more run to packit to see what's wrong. Otherwise the PR looks good.

**Comment by inknos** [comment]
the issue looks unrelated to me

/lgtm
/approve

**Review by inknos — APPROVED** [review]

**Comment by inknos** [comment]
right, I am not approver in this branch. could you take a look? @jwhonce @lsm5

**Review by lsm5 — APPROVED** [review]
LGTM. the centos 9 stream aarch64 failure will take a while to go away because of mirror propagation. But x86_64 passed and this is noarch so we're good to go.

/lgtm
/hold

**Comment by lsm5** [comment]
> right, I am not approver in this branch. could you take a look? @jwhonce @lsm5

@inknos Feel free to add yourself. I'll approve and merge.

**Pull request merged**
