### PR TITLE
Bump to version 4.2.0

### PR DESCRIPTION
**Pull request by cdoern**
Signed-off-by: Charlie Doern <cdoern@redhat.com>

### CODE REVIEW

**Comment by cdoern** [comment]
@lsm5 @umohnani8 PTAL. I think I did this correctly.

**Comment by rhatdan** [comment]
Why is this going to 4.2 rather then 4.1?

**Comment by rhatdan** [comment]
Looks like tests are not happy?

**Comment by cdoern** [comment]
I was under the assumption that we were bumping in lock step with podman. Are we supposed to be a release behind?

**Comment by rhatdan** [comment]
No Idea, I guess we never released for podman 4.1, So I am fine with the bump.  Just curious.
Matching podman versions, will probably make it easier for users to understand.

**Comment by lsm5** [comment]
@cdoern LGTM, though I checked out your PR and don't see a git tag against the commit. If you're planning to do that post-merge, that's fine

**Comment by lsm5** [comment]
> No Idea, I guess we never released for podman 4.1, So I am fine with the bump. Just curious. Matching podman versions, will probably make it easier for users to understand.

Agreed.

**Comment by lsm5** [comment]
> @cdoern LGTM, though I checked out your PR and don't see a git tag against the commit. If you're planning to do that post-merge, that's fine

@cdoern that was my bad. Looks like `gh checkout #PR_NUM` doesn't fetch the tag. I added your fork as remote and then fetched the tag. LGTM

**Comment by umohnani8** [comment]
LGTM

Does the bot merge this or do we have to do it manually

**Comment by lsm5** [comment]
> LGTM
> 
> Does the bot merge this or do we have to do it manually

@cdoern mentioned prior commits were manually merged, so I merged it just now.

On some other repos though I've seen the bot take its own time before doing the merge.

**Pull request merged**
