### PR TITLE
Build progress via Generator

### LINKED ISSUE #171: Stream option for pulling images
Hey,

Didn't know where to write it, because the change is needed between podman-py and podman REST Api, but as I'm not that familiar with podman REST Api source (honestly podman project is so complex I can't find definitions of the REST endpoints there :|) I decided to write here.

I'm wondering whether `stream` option could be a part of podman-py at some point.
In [docker-py there was such functionality](https://docker-py.readthedocs.io/en/stable/api.html) (stream (bool) – Stream the output as a generator. Make sure to consume the generator, otherwise pull might get cancelled.)
Thanks to it, it was possible to show progress of pulling images to the user, which is a cool and useful feature (note that regular `podman pull` does it by default).

The information about progress is actually somewhat there.
To prove that I've added one simple `print(body)` [here](https://github.com/containers/podman-py/blob/main/podman/domain/images_manager.py#L312).
Which showed such output : 
```
>>> import podman
>>> client = podman.PodmanClient(base_url='unix:///run/podman/podman.sock')
>>> image = client.images.pull(repository='ubi8', tag='latest')
{'stream': 'Trying to pull ubi8:latest...\n'}
{'stream': 'Getting image source signatures\n'}
{'stream': 'Copying blob sha256:3de00bb8554b2c35c89412d5336f1fa469afc7b0160045dd08758d92c8a6b064\n'}
{'stream': 'Copying blob sha256:3de00bb8554b2c35c89412d5336f1fa469afc7b0160045dd08758d92c8a6b064\n'}
{'stream': 'Copying blob sha256:c530010fb61c513e7f06fa29484418fabf62924fc80cc8183ab671a3ce461a8e\n'}
{'stream': 'Copying blob sha256:c530010fb61c513e7f06fa29484418fabf62924fc80cc8183ab671a3ce461a8e\n'}
{'stream': 'Copying config sha256:552ac8ae4291e2a8d5622cff4a7f978d3032664b3946831a5606bde9bdedef2a\n'}
{'stream': 'Writing manifest to image destination\n'}
{'stream': 'Storing signatures\n'}
{'images': ['552ac8ae4291e2a8d5622cff4a7f978d3032664b3946831a5606bde9bdedef2a'], 'id': '552ac8ae4291e2a8d5622cff4a7f978d3032664b3946831a5606bde9bdedef2a'}
```

Unfortunately all of this prints are showed **after** image is pulled as the `/images/pull` is a blocking method.
I've tried [similar method to logs](https://github.com/containers/podman-py/pull/162/files) with `stream=True` and `api.stream_frames` and even though it returned generator, the generator was filled **after** image was pulled.

My question is whether it is doable with current REST Api ?
Or are the changes on podman REST Api needed ?

### PR DESCRIPTION
**Pull request by jwhonce**
* Present service progress to caller when using Build().
* Update changed black options

Closes #171

Signed-off-by: Jhon Honce <jhonce@redhat.com>

### CODE REVIEW

**Comment by msisj** [comment]
@jwhonce 

Nice! Your solution works.
I must have missed that combination (stream=True and no `api.stream_frames`) during testing - my bad.

To be honest, in order to keep compatibility with docker-py, give user access to real-time logs and to not break current API I'd : 

1. Add `stream=False` option to `pull` method
2. set stream=stream in `/images/pull` REST method
3. `if stream is True` -> `return response.iter_lines()` so that generator is returned giving user option to parse it in real time (that's how docker-py handled that)

**Comment by jwhonce** [comment]
@msisj  I was writing to their higher level API which does not have the `stream` keyword [documented](https://docker-py.readthedocs.io/en/stable/images.html#docker.models.images.ImageCollection.pull). I am happy to go with the solution you describe as it does not break the API either.

**Comment by msisj** [comment]
@jwhonce 
As I've worked quite a bit with docker-py I'm kind of familiar with their documentation, which has weird interface (regular one and the other for low level api) for documentation.
To get to the real stuff one has to click `Low-level API` where we can find https://docker-py.readthedocs.io/en/stable/api.html#docker.api.image.ImageApiMixin.pull which has these options described.

Also I can see that your `Gating test` has failed on pylint. I'm having similar issue under https://github.com/containers/podman-py/pull/172 . What I can see is that for some reason pylint fails on files which were not touched in the PR. My guess it that some code was merged, which introduced these failures, without passing pylint. Could you take a look at it?

**Comment by msisj** [comment]
@jwhonce 
Also I've got another question, is there a possibility to get the actual progress of the image being pulled ? (like we get in podman pull command; docker-py actually showed that level of details) : 
```
Copying blob 2f408cfwf45f [=======>------------------------------] 104.9MiB / 530.8MiB
```

**Comment by msisj** [comment]
@jwhonce 
Also I've got another question, is there a possibility to get the actual progress of the image being pulled ? (like we get in podman pull command; docker-py actually showed that level of details) : 
```
Copying blob 2f408cfwf45f [=======>------------------------------] 104.9MiB / 530.8MiB
```

**Review by mwhahaha — APPROVED** [review]
lgtm

**Pull request merged**
